#ifndef MODEL__H
#define MODEL__H
#include "weight2.h"
#include "model.h"
#include "node.h"
// Creates tensors for the model
// If return is 0, function fail. Success if return is 1
int create_model2_onnx_tensor() { 
	_tensor= create_tensor(_array, 1, _dim,1, INT64, true);
	if(_tensor == NULL )return NULL;
	_v_105_tensor= create_tensor(_v_105_array, 2, _v_105_dim,1, INT64, true);
	if(_v_105_tensor == NULL )return NULL;
	_v_106_tensor= create_tensor(_v_106_array, 2, _v_106_dim,1, INT64, true);
	if(_v_106_tensor == NULL )return NULL;
	_v_107_tensor= create_tensor(_v_107_array, 2, _v_107_dim,1, INT64, true);
	if(_v_107_tensor == NULL )return NULL;
	_v_108_tensor= create_tensor(_v_108_array, 2, _v_108_dim,1, INT64, true);
	if(_v_108_tensor == NULL )return NULL;
	_v_109_tensor= create_tensor(_v_109_array, 1, _v_109_dim,1, INT64, true);
	if(_v_109_tensor == NULL )return NULL;
	_v_110_tensor= create_tensor(_v_110_array, 1, _v_110_dim,1, INT64, true);
	if(_v_110_tensor == NULL )return NULL;
	_v_111_tensor= create_tensor(_v_111_array, 1, _v_111_dim,1, INT64, true);
	if(_v_111_tensor == NULL )return NULL;
	_v_112_tensor= create_tensor(_v_112_array, 1, _v_112_dim,1, INT64, true);
	if(_v_112_tensor == NULL )return NULL;
	_v_113_tensor= create_tensor(_v_113_array, 1, _v_113_dim,1, INT64, true);
	if(_v_113_tensor == NULL )return NULL;
	_v_114_tensor= create_tensor(_v_114_array, 1, _v_114_dim,1, INT64, true);
	if(_v_114_tensor == NULL )return NULL;
	_v_115_tensor= create_tensor(_v_115_array, 1, _v_115_dim,1, INT64, true);
	if(_v_115_tensor == NULL )return NULL;
	_v_116_tensor= create_tensor(_v_116_array, 1, _v_116_dim,1, INT64, true);
	if(_v_116_tensor == NULL )return NULL;
	_v_117_tensor= create_tensor(_v_117_array, 1, _v_117_dim,1, INT64, true);
	if(_v_117_tensor == NULL )return NULL;
	_v_118_tensor= create_tensor(_v_118_array, 1, _v_118_dim,1, INT64, true);
	if(_v_118_tensor == NULL )return NULL;
	_v_119_tensor= create_tensor(_v_119_array, 1, _v_119_dim,1, INT64, true);
	if(_v_119_tensor == NULL )return NULL;
	_v_120_tensor= create_tensor(_v_120_array, 1, _v_120_dim,1, INT64, true);
	if(_v_120_tensor == NULL )return NULL;
	adjusted_input_tensor= create_tensor(adjusted_input_array, 256, adjusted_input_dim,3, FLOAT32, true);
	if(adjusted_input_tensor == NULL )return NULL;
	adjusted_input1_tensor= create_tensor(adjusted_input1_array, 512, adjusted_input1_dim,3, FLOAT32, true);
	if(adjusted_input1_tensor == NULL )return NULL;
	conv1d_2_kernel_0_tensor= create_tensor(conv1d_2_kernel_0_array, 131072, conv1d_2_kernel_0_dim,3, FLOAT32, true);
	if(conv1d_2_kernel_0_tensor == NULL )return NULL;
	conv1d_3_tensor= create_tensor(conv1d_3_array, 512, conv1d_3_dim,3, FLOAT32, true);
	if(conv1d_3_tensor == NULL )return NULL;
	conv1d_3_kernel_0_tensor= create_tensor(conv1d_3_kernel_0_array, 131072, conv1d_3_kernel_0_dim,3, FLOAT32, true);
	if(conv1d_3_kernel_0_tensor == NULL )return NULL;
	convolution_output_tensor= create_tensor(convolution_output_array, 512, convolution_output_dim,3, FLOAT32, true);
	if(convolution_output_tensor == NULL )return NULL;
	convolution_output1_tensor= create_tensor(convolution_output1_array, 256, convolution_output1_dim,3, FLOAT32, true);
	if(convolution_output1_tensor == NULL )return NULL;
	input_4_tensor= create_tensor(input_4_array, 512, input_4_dim,3, FLOAT32, true);
	if(input_4_tensor == NULL )return NULL;
	input_5_tensor= create_tensor(input_5_array, 512, input_5_dim,4, FLOAT32, true);
	if(input_5_tensor == NULL )return NULL;
	input_5_01_cropping0_tensor= create_tensor(input_5_01_cropping0_array, 128, input_5_01_cropping0_dim,4, FLOAT32, true);
	if(input_5_01_cropping0_tensor == NULL )return NULL;
	input_5_01_cropping01_tensor= create_tensor(input_5_01_cropping01_array, 128, input_5_01_cropping01_dim,4, FLOAT32, true);
	if(input_5_01_cropping01_tensor == NULL )return NULL;
	input_5_01_cropping02_tensor= create_tensor(input_5_01_cropping02_array, 128, input_5_01_cropping02_dim,4, FLOAT32, true);
	if(input_5_01_cropping02_tensor == NULL )return NULL;
	input_5_01_cropping03_tensor= create_tensor(input_5_01_cropping03_array, 128, input_5_01_cropping03_dim,4, FLOAT32, true);
	if(input_5_01_cropping03_tensor == NULL )return NULL;
	input_5_01_cropping_axes_tensor= create_tensor(input_5_01_cropping_axes_array, 4, input_5_01_cropping_axes_dim,1, INT64, true);
	if(input_5_01_cropping_axes_tensor == NULL )return NULL;
	input_5_01_cropping_end_tensor= create_tensor(input_5_01_cropping_end_array, 4, input_5_01_cropping_end_dim,1, INT64, true);
	if(input_5_01_cropping_end_tensor == NULL )return NULL;
	input_5_01_cropping_end1_tensor= create_tensor(input_5_01_cropping_end1_array, 4, input_5_01_cropping_end1_dim,1, INT64, true);
	if(input_5_01_cropping_end1_tensor == NULL )return NULL;
	input_5_01_cropping_end2_tensor= create_tensor(input_5_01_cropping_end2_array, 4, input_5_01_cropping_end2_dim,1, INT64, true);
	if(input_5_01_cropping_end2_tensor == NULL )return NULL;
	input_5_01_cropping_end3_tensor= create_tensor(input_5_01_cropping_end3_array, 4, input_5_01_cropping_end3_dim,1, INT64, true);
	if(input_5_01_cropping_end3_tensor == NULL )return NULL;
	input_5_01_cropping_start_tensor= create_tensor(input_5_01_cropping_start_array, 4, input_5_01_cropping_start_dim,1, INT64, true);
	if(input_5_01_cropping_start_tensor == NULL )return NULL;
	input_5_01_cropping_start1_tensor= create_tensor(input_5_01_cropping_start1_array, 4, input_5_01_cropping_start1_dim,1, INT64, true);
	if(input_5_01_cropping_start1_tensor == NULL )return NULL;
	input_5_01_cropping_start2_tensor= create_tensor(input_5_01_cropping_start2_array, 4, input_5_01_cropping_start2_dim,1, INT64, true);
	if(input_5_01_cropping_start2_tensor == NULL )return NULL;
	input_5_01_cropping_start3_tensor= create_tensor(input_5_01_cropping_start3_array, 4, input_5_01_cropping_start3_dim,1, INT64, true);
	if(input_5_01_cropping_start3_tensor == NULL )return NULL;
	input_5_01_cropping_steps_tensor= create_tensor(input_5_01_cropping_steps_array, 4, input_5_01_cropping_steps_dim,1, INT64, true);
	if(input_5_01_cropping_steps_tensor == NULL )return NULL;
	model_2_activation_3_Sigmoid_0_tensor= create_tensor(model_2_activation_3_Sigmoid_0_array, 256, model_2_activation_3_Sigmoid_0_dim,3, FLOAT32, true);
	if(model_2_activation_3_Sigmoid_0_tensor == NULL )return NULL;
	model_2_dense_3_BiasAdd_ReadVariableOp_resource_0_tensor= create_tensor(model_2_dense_3_BiasAdd_ReadVariableOp_resource_0_array, 256, model_2_dense_3_BiasAdd_ReadVariableOp_resource_0_dim,1, FLOAT32, true);
	if(model_2_dense_3_BiasAdd_ReadVariableOp_resource_0_tensor == NULL )return NULL;
	model_2_dense_3_BiasAdd_0_tensor= create_tensor(model_2_dense_3_BiasAdd_0_array, 256, model_2_dense_3_BiasAdd_0_dim,3, FLOAT32, true);
	if(model_2_dense_3_BiasAdd_0_tensor == NULL )return NULL;
	model_2_dense_3_Tensordot_MatMul_0_tensor= create_tensor(model_2_dense_3_Tensordot_MatMul_0_array, 256, model_2_dense_3_Tensordot_MatMul_0_dim,2, FLOAT32, true);
	if(model_2_dense_3_Tensordot_MatMul_0_tensor == NULL )return NULL;
	model_2_dense_3_Tensordot_Reshape_0_tensor= create_tensor(model_2_dense_3_Tensordot_Reshape_0_array, 128, model_2_dense_3_Tensordot_Reshape_0_dim,2, FLOAT32, true);
	if(model_2_dense_3_Tensordot_Reshape_0_tensor == NULL )return NULL;
	model_2_dense_3_Tensordot_Reshape_1_0_tensor= create_tensor(model_2_dense_3_Tensordot_Reshape_1_0_array, 32768, model_2_dense_3_Tensordot_Reshape_1_0_dim,2, FLOAT32, true);
	if(model_2_dense_3_Tensordot_Reshape_1_0_tensor == NULL )return NULL;
	model_2_dense_3_Tensordot_0_tensor= create_tensor(model_2_dense_3_Tensordot_0_array, 256, model_2_dense_3_Tensordot_0_dim,3, FLOAT32, true);
	if(model_2_dense_3_Tensordot_0_tensor == NULL )return NULL;
	model_2_instant_layer_normalization_1_Mean_0_tensor= create_tensor(model_2_instant_layer_normalization_1_Mean_0_array, 256, model_2_instant_layer_normalization_1_Mean_0_dim,3, FLOAT32, true);
	if(model_2_instant_layer_normalization_1_Mean_0_tensor == NULL )return NULL;
	model_2_instant_layer_normalization_1_Mean_1_0_tensor= create_tensor(model_2_instant_layer_normalization_1_Mean_1_0_array, 256, model_2_instant_layer_normalization_1_Mean_1_0_dim,3, FLOAT32, true);
	if(model_2_instant_layer_normalization_1_Mean_1_0_tensor == NULL )return NULL;
	model_2_instant_layer_normalization_1_Sqrt_0_tensor= create_tensor(model_2_instant_layer_normalization_1_Sqrt_0_array, 256, model_2_instant_layer_normalization_1_Sqrt_0_dim,3, FLOAT32, true);
	if(model_2_instant_layer_normalization_1_Sqrt_0_tensor == NULL )return NULL;
	model_2_instant_layer_normalization_1_Square_0_tensor= create_tensor(model_2_instant_layer_normalization_1_Square_0_array, 256, model_2_instant_layer_normalization_1_Square_0_dim,3, FLOAT32, true);
	if(model_2_instant_layer_normalization_1_Square_0_tensor == NULL )return NULL;
	model_2_instant_layer_normalization_1_add_y_0_tensor= create_tensor(model_2_instant_layer_normalization_1_add_y_0_array, 1, model_2_instant_layer_normalization_1_add_y_0_dim,1, FLOAT32, true);
	if(model_2_instant_layer_normalization_1_add_y_0_tensor == NULL )return NULL;
	model_2_instant_layer_normalization_1_add_0_tensor= create_tensor(model_2_instant_layer_normalization_1_add_0_array, 256, model_2_instant_layer_normalization_1_add_0_dim,3, FLOAT32, true);
	if(model_2_instant_layer_normalization_1_add_0_tensor == NULL )return NULL;
	model_2_instant_layer_normalization_1_add_1_ReadVariableOp_resource_0_tensor= create_tensor(model_2_instant_layer_normalization_1_add_1_ReadVariableOp_resource_0_array, 256, model_2_instant_layer_normalization_1_add_1_ReadVariableOp_resource_0_dim,1, FLOAT32, true);
	if(model_2_instant_layer_normalization_1_add_1_ReadVariableOp_resource_0_tensor == NULL )return NULL;
	model_2_instant_layer_normalization_1_add_1_0_tensor= create_tensor(model_2_instant_layer_normalization_1_add_1_0_array, 256, model_2_instant_layer_normalization_1_add_1_0_dim,3, FLOAT32, true);
	if(model_2_instant_layer_normalization_1_add_1_0_tensor == NULL )return NULL;
	model_2_instant_layer_normalization_1_mul_ReadVariableOp_resource_0_tensor= create_tensor(model_2_instant_layer_normalization_1_mul_ReadVariableOp_resource_0_array, 256, model_2_instant_layer_normalization_1_mul_ReadVariableOp_resource_0_dim,1, FLOAT32, true);
	if(model_2_instant_layer_normalization_1_mul_ReadVariableOp_resource_0_tensor == NULL )return NULL;
	model_2_instant_layer_normalization_1_mul_0_tensor= create_tensor(model_2_instant_layer_normalization_1_mul_0_array, 256, model_2_instant_layer_normalization_1_mul_0_dim,3, FLOAT32, true);
	if(model_2_instant_layer_normalization_1_mul_0_tensor == NULL )return NULL;
	model_2_instant_layer_normalization_1_sub_1_0_tensor= create_tensor(model_2_instant_layer_normalization_1_sub_1_0_array, 256, model_2_instant_layer_normalization_1_sub_1_0_dim,3, FLOAT32, true);
	if(model_2_instant_layer_normalization_1_sub_1_0_tensor == NULL )return NULL;
	model_2_instant_layer_normalization_1_truediv_0_tensor= create_tensor(model_2_instant_layer_normalization_1_truediv_0_array, 256, model_2_instant_layer_normalization_1_truediv_0_dim,3, FLOAT32, true);
	if(model_2_instant_layer_normalization_1_truediv_0_tensor == NULL )return NULL;
	model_2_lstm_6_BiasAdd_ReadVariableOp_resource_0_tensor= create_tensor(model_2_lstm_6_BiasAdd_ReadVariableOp_resource_0_array, 512, model_2_lstm_6_BiasAdd_ReadVariableOp_resource_0_dim,1, FLOAT32, true);
	if(model_2_lstm_6_BiasAdd_ReadVariableOp_resource_0_tensor == NULL )return NULL;
	model_2_lstm_6_BiasAdd_0_tensor= create_tensor(model_2_lstm_6_BiasAdd_0_array, 512, model_2_lstm_6_BiasAdd_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_BiasAdd_0_tensor == NULL )return NULL;
	model_2_lstm_6_MatMul_ReadVariableOp_resource_0_tensor= create_tensor(model_2_lstm_6_MatMul_ReadVariableOp_resource_0_array, 131072, model_2_lstm_6_MatMul_ReadVariableOp_resource_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_MatMul_ReadVariableOp_resource_0_tensor == NULL )return NULL;
	model_2_lstm_6_MatMul_1_ReadVariableOp_resource_0_tensor= create_tensor(model_2_lstm_6_MatMul_1_ReadVariableOp_resource_0_array, 65536, model_2_lstm_6_MatMul_1_ReadVariableOp_resource_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_MatMul_1_ReadVariableOp_resource_0_tensor == NULL )return NULL;
	model_2_lstm_6_MatMul_1_0_tensor= create_tensor(model_2_lstm_6_MatMul_1_0_array, 512, model_2_lstm_6_MatMul_1_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_MatMul_1_0_tensor == NULL )return NULL;
	model_2_lstm_6_Sigmoid_0_tensor= create_tensor(model_2_lstm_6_Sigmoid_0_array, 128, model_2_lstm_6_Sigmoid_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_Sigmoid_0_tensor == NULL )return NULL;
	model_2_lstm_6_Sigmoid_1_0_tensor= create_tensor(model_2_lstm_6_Sigmoid_1_0_array, 128, model_2_lstm_6_Sigmoid_1_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_Sigmoid_1_0_tensor == NULL )return NULL;
	model_2_lstm_6_Sigmoid_2_0_tensor= create_tensor(model_2_lstm_6_Sigmoid_2_0_array, 128, model_2_lstm_6_Sigmoid_2_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_Sigmoid_2_0_tensor == NULL )return NULL;
	model_2_lstm_6_Tanh_0_tensor= create_tensor(model_2_lstm_6_Tanh_0_array, 128, model_2_lstm_6_Tanh_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_Tanh_0_tensor == NULL )return NULL;
	model_2_lstm_6_Tanh_1_0_tensor= create_tensor(model_2_lstm_6_Tanh_1_0_array, 128, model_2_lstm_6_Tanh_1_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_Tanh_1_0_tensor == NULL )return NULL;
	model_2_lstm_6_add_0_tensor= create_tensor(model_2_lstm_6_add_0_array, 512, model_2_lstm_6_add_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_add_0_tensor == NULL )return NULL;
	model_2_lstm_6_add_1_0_tensor= create_tensor(model_2_lstm_6_add_1_0_array, 128, model_2_lstm_6_add_1_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_add_1_0_tensor == NULL )return NULL;
	model_2_lstm_6_mul_0_tensor= create_tensor(model_2_lstm_6_mul_0_array, 128, model_2_lstm_6_mul_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_mul_0_tensor == NULL )return NULL;
	model_2_lstm_6_mul_1_0_tensor= create_tensor(model_2_lstm_6_mul_1_0_array, 128, model_2_lstm_6_mul_1_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_mul_1_0_tensor == NULL )return NULL;
	model_2_lstm_6_mul_2_0_tensor= create_tensor(model_2_lstm_6_mul_2_0_array, 128, model_2_lstm_6_mul_2_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_mul_2_0_tensor == NULL )return NULL;
	model_2_lstm_6_split_0_tensor= create_tensor(model_2_lstm_6_split_0_array, 128, model_2_lstm_6_split_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_split_0_tensor == NULL )return NULL;
	model_2_lstm_6_split_1_tensor= create_tensor(model_2_lstm_6_split_1_array, 128, model_2_lstm_6_split_1_dim,2, FLOAT32, true);
	if(model_2_lstm_6_split_1_tensor == NULL )return NULL;
	model_2_lstm_6_split_2_tensor= create_tensor(model_2_lstm_6_split_2_array, 128, model_2_lstm_6_split_2_dim,2, FLOAT32, true);
	if(model_2_lstm_6_split_2_tensor == NULL )return NULL;
	model_2_lstm_6_split_3_tensor= create_tensor(model_2_lstm_6_split_3_array, 128, model_2_lstm_6_split_3_dim,2, FLOAT32, true);
	if(model_2_lstm_6_split_3_tensor == NULL )return NULL;
	model_2_lstm_6_stack_unsqueeze00_tensor= create_tensor(model_2_lstm_6_stack_unsqueeze00_array, 128, model_2_lstm_6_stack_unsqueeze00_dim,3, FLOAT32, true);
	if(model_2_lstm_6_stack_unsqueeze00_tensor == NULL )return NULL;
	model_2_lstm_6_transpose_0_tensor= create_tensor(model_2_lstm_6_transpose_0_array, 256, model_2_lstm_6_transpose_0_dim,3, FLOAT32, true);
	if(model_2_lstm_6_transpose_0_tensor == NULL )return NULL;
	model_2_lstm_6_unstack_0_tensor= create_tensor(model_2_lstm_6_unstack_0_array, 256, model_2_lstm_6_unstack_0_dim,2, FLOAT32, true);
	if(model_2_lstm_6_unstack_0_tensor == NULL )return NULL;
	model_2_lstm_7_BiasAdd_ReadVariableOp_resource_0_tensor= create_tensor(model_2_lstm_7_BiasAdd_ReadVariableOp_resource_0_array, 512, model_2_lstm_7_BiasAdd_ReadVariableOp_resource_0_dim,1, FLOAT32, true);
	if(model_2_lstm_7_BiasAdd_ReadVariableOp_resource_0_tensor == NULL )return NULL;
	model_2_lstm_7_BiasAdd_0_tensor= create_tensor(model_2_lstm_7_BiasAdd_0_array, 512, model_2_lstm_7_BiasAdd_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_BiasAdd_0_tensor == NULL )return NULL;
	model_2_lstm_7_MatMul_ReadVariableOp_resource_0_tensor= create_tensor(model_2_lstm_7_MatMul_ReadVariableOp_resource_0_array, 65536, model_2_lstm_7_MatMul_ReadVariableOp_resource_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_MatMul_ReadVariableOp_resource_0_tensor == NULL )return NULL;
	model_2_lstm_7_MatMul_1_ReadVariableOp_resource_0_tensor= create_tensor(model_2_lstm_7_MatMul_1_ReadVariableOp_resource_0_array, 65536, model_2_lstm_7_MatMul_1_ReadVariableOp_resource_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_MatMul_1_ReadVariableOp_resource_0_tensor == NULL )return NULL;
	model_2_lstm_7_MatMul_1_0_tensor= create_tensor(model_2_lstm_7_MatMul_1_0_array, 512, model_2_lstm_7_MatMul_1_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_MatMul_1_0_tensor == NULL )return NULL;
	model_2_lstm_7_Sigmoid_0_tensor= create_tensor(model_2_lstm_7_Sigmoid_0_array, 128, model_2_lstm_7_Sigmoid_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_Sigmoid_0_tensor == NULL )return NULL;
	model_2_lstm_7_Sigmoid_1_0_tensor= create_tensor(model_2_lstm_7_Sigmoid_1_0_array, 128, model_2_lstm_7_Sigmoid_1_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_Sigmoid_1_0_tensor == NULL )return NULL;
	model_2_lstm_7_Sigmoid_2_0_tensor= create_tensor(model_2_lstm_7_Sigmoid_2_0_array, 128, model_2_lstm_7_Sigmoid_2_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_Sigmoid_2_0_tensor == NULL )return NULL;
	model_2_lstm_7_Tanh_0_tensor= create_tensor(model_2_lstm_7_Tanh_0_array, 128, model_2_lstm_7_Tanh_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_Tanh_0_tensor == NULL )return NULL;
	model_2_lstm_7_Tanh_1_0_tensor= create_tensor(model_2_lstm_7_Tanh_1_0_array, 128, model_2_lstm_7_Tanh_1_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_Tanh_1_0_tensor == NULL )return NULL;
	model_2_lstm_7_add_0_tensor= create_tensor(model_2_lstm_7_add_0_array, 512, model_2_lstm_7_add_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_add_0_tensor == NULL )return NULL;
	model_2_lstm_7_add_1_0_tensor= create_tensor(model_2_lstm_7_add_1_0_array, 128, model_2_lstm_7_add_1_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_add_1_0_tensor == NULL )return NULL;
	model_2_lstm_7_mul_0_tensor= create_tensor(model_2_lstm_7_mul_0_array, 128, model_2_lstm_7_mul_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_mul_0_tensor == NULL )return NULL;
	model_2_lstm_7_mul_1_0_tensor= create_tensor(model_2_lstm_7_mul_1_0_array, 128, model_2_lstm_7_mul_1_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_mul_1_0_tensor == NULL )return NULL;
	model_2_lstm_7_mul_2_0_tensor= create_tensor(model_2_lstm_7_mul_2_0_array, 128, model_2_lstm_7_mul_2_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_mul_2_0_tensor == NULL )return NULL;
	model_2_lstm_7_split_0_tensor= create_tensor(model_2_lstm_7_split_0_array, 128, model_2_lstm_7_split_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_split_0_tensor == NULL )return NULL;
	model_2_lstm_7_split_1_tensor= create_tensor(model_2_lstm_7_split_1_array, 128, model_2_lstm_7_split_1_dim,2, FLOAT32, true);
	if(model_2_lstm_7_split_1_tensor == NULL )return NULL;
	model_2_lstm_7_split_2_tensor= create_tensor(model_2_lstm_7_split_2_array, 128, model_2_lstm_7_split_2_dim,2, FLOAT32, true);
	if(model_2_lstm_7_split_2_tensor == NULL )return NULL;
	model_2_lstm_7_split_3_tensor= create_tensor(model_2_lstm_7_split_3_array, 128, model_2_lstm_7_split_3_dim,2, FLOAT32, true);
	if(model_2_lstm_7_split_3_tensor == NULL )return NULL;
	model_2_lstm_7_stack_unsqueeze00_tensor= create_tensor(model_2_lstm_7_stack_unsqueeze00_array, 128, model_2_lstm_7_stack_unsqueeze00_dim,3, FLOAT32, true);
	if(model_2_lstm_7_stack_unsqueeze00_tensor == NULL )return NULL;
	model_2_lstm_7_transpose_1_0_tensor= create_tensor(model_2_lstm_7_transpose_1_0_array, 128, model_2_lstm_7_transpose_1_0_dim,3, FLOAT32, true);
	if(model_2_lstm_7_transpose_1_0_tensor == NULL )return NULL;
	model_2_lstm_7_unstack_0_tensor= create_tensor(model_2_lstm_7_unstack_0_array, 128, model_2_lstm_7_unstack_0_dim,2, FLOAT32, true);
	if(model_2_lstm_7_unstack_0_tensor == NULL )return NULL;
	model_2_multiply_2_mul_0_tensor= create_tensor(model_2_multiply_2_mul_0_array, 256, model_2_multiply_2_mul_0_dim,3, FLOAT32, true);
	if(model_2_multiply_2_mul_0_tensor == NULL )return NULL;
	model_2_tf_op_layer_stack_3_stack_3_0_tensor= create_tensor(model_2_tf_op_layer_stack_3_stack_3_0_array, 256, model_2_tf_op_layer_stack_3_stack_3_0_dim,3, FLOAT32, true);
	if(model_2_tf_op_layer_stack_3_stack_3_0_tensor == NULL )return NULL;
	model_2_tf_op_layer_stack_3_stack_3_unsqueeze00_tensor= create_tensor(model_2_tf_op_layer_stack_3_stack_3_unsqueeze00_array, 128, model_2_tf_op_layer_stack_3_stack_3_unsqueeze00_dim,3, FLOAT32, true);
	if(model_2_tf_op_layer_stack_3_stack_3_unsqueeze00_tensor == NULL )return NULL;
	model_2_tf_op_layer_stack_3_stack_3_unsqueeze10_tensor= create_tensor(model_2_tf_op_layer_stack_3_stack_3_unsqueeze10_array, 128, model_2_tf_op_layer_stack_3_stack_3_unsqueeze10_dim,3, FLOAT32, true);
	if(model_2_tf_op_layer_stack_3_stack_3_unsqueeze10_tensor == NULL )return NULL;
	model_2_tf_op_layer_stack_4_stack_4_0_tensor= create_tensor(model_2_tf_op_layer_stack_4_stack_4_0_array, 256, model_2_tf_op_layer_stack_4_stack_4_0_dim,3, FLOAT32, true);
	if(model_2_tf_op_layer_stack_4_stack_4_0_tensor == NULL )return NULL;
	model_2_tf_op_layer_stack_4_stack_4_unsqueeze00_tensor= create_tensor(model_2_tf_op_layer_stack_4_stack_4_unsqueeze00_array, 128, model_2_tf_op_layer_stack_4_stack_4_unsqueeze00_dim,3, FLOAT32, true);
	if(model_2_tf_op_layer_stack_4_stack_4_unsqueeze00_tensor == NULL )return NULL;
	model_2_tf_op_layer_stack_4_stack_4_unsqueeze10_tensor= create_tensor(model_2_tf_op_layer_stack_4_stack_4_unsqueeze10_array, 128, model_2_tf_op_layer_stack_4_stack_4_unsqueeze10_dim,3, FLOAT32, true);
	if(model_2_tf_op_layer_stack_4_stack_4_unsqueeze10_tensor == NULL )return NULL;
	model_2_tf_op_layer_stack_5_stack_5_unsqueeze00_tensor= create_tensor(model_2_tf_op_layer_stack_5_stack_5_unsqueeze00_array, 256, model_2_tf_op_layer_stack_5_stack_5_unsqueeze00_dim,4, FLOAT32, true);
	if(model_2_tf_op_layer_stack_5_stack_5_unsqueeze00_tensor == NULL )return NULL;
	model_2_tf_op_layer_stack_5_stack_5_unsqueeze10_tensor= create_tensor(model_2_tf_op_layer_stack_5_stack_5_unsqueeze10_array, 256, model_2_tf_op_layer_stack_5_stack_5_unsqueeze10_dim,4, FLOAT32, true);
	if(model_2_tf_op_layer_stack_5_stack_5_unsqueeze10_tensor == NULL )return NULL;
	model_2_tf_op_layer_strided_slice_4_strided_slice_4_0_tensor= create_tensor(model_2_tf_op_layer_strided_slice_4_strided_slice_4_0_array, 128, model_2_tf_op_layer_strided_slice_4_strided_slice_4_0_dim,2, FLOAT32, true);
	if(model_2_tf_op_layer_strided_slice_4_strided_slice_4_0_tensor == NULL )return NULL;
	model_2_tf_op_layer_strided_slice_5_strided_slice_5_0_tensor= create_tensor(model_2_tf_op_layer_strided_slice_5_strided_slice_5_0_array, 128, model_2_tf_op_layer_strided_slice_5_strided_slice_5_0_dim,2, FLOAT32, true);
	if(model_2_tf_op_layer_strided_slice_5_strided_slice_5_0_tensor == NULL )return NULL;
	model_2_tf_op_layer_strided_slice_6_strided_slice_6_0_tensor= create_tensor(model_2_tf_op_layer_strided_slice_6_strided_slice_6_0_array, 128, model_2_tf_op_layer_strided_slice_6_strided_slice_6_0_dim,2, FLOAT32, true);
	if(model_2_tf_op_layer_strided_slice_6_strided_slice_6_0_tensor == NULL )return NULL;
	model_2_tf_op_layer_strided_slice_7_strided_slice_7_0_tensor= create_tensor(model_2_tf_op_layer_strided_slice_7_strided_slice_7_0_array, 128, model_2_tf_op_layer_strided_slice_7_strided_slice_7_0_dim,2, FLOAT32, true);
	if(model_2_tf_op_layer_strided_slice_7_strided_slice_7_0_tensor == NULL )return NULL;
	shape_tensor_tensor= create_tensor(shape_tensor_array, 3, shape_tensor_dim,1, INT64, true);
	if(shape_tensor_tensor == NULL )return NULL;
	shape_tensor1_tensor= create_tensor(shape_tensor1_array, 2, shape_tensor1_dim,1, INT64, true);
	if(shape_tensor1_tensor == NULL )return NULL;
	tf_op_layer_stack_5_tensor= create_tensor(tf_op_layer_stack_5_array, 512, tf_op_layer_stack_5_dim,4, FLOAT32, true);
	if(tf_op_layer_stack_5_tensor == NULL )return NULL;
	transpose_output1_tensor= create_tensor(transpose_output1_array, 256, transpose_output1_dim,3, FLOAT32, true);
	if(transpose_output1_tensor == NULL )return NULL;
	return 1;
	}

int create_model2_onnx_attributes(){ 
	return 1;
	} 

// Use malloc to create struct model, then call this function on the model
int setup_model2_onnx( struct model* m){
	if(m == NULL) return 0;// Input is null
	struct node* new_node = NULL;
	/*        node creation        */
	new_node = create_transpose_node( Transpose2_perm, input_4_tensor, adjusted_input1_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_slice_node( input_5_tensor, input_5_01_cropping_start_tensor, input_5_01_cropping_end_tensor, input_5_01_cropping_axes_tensor, input_5_01_cropping_steps_tensor, input_5_01_cropping0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_slice_node( input_5_tensor, input_5_01_cropping_start1_tensor, input_5_01_cropping_end1_tensor, input_5_01_cropping_axes_tensor, input_5_01_cropping_steps_tensor, input_5_01_cropping01_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_slice_node( input_5_tensor, input_5_01_cropping_start2_tensor, input_5_01_cropping_end2_tensor, input_5_01_cropping_axes_tensor, input_5_01_cropping_steps_tensor, input_5_01_cropping02_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_slice_node( input_5_tensor, input_5_01_cropping_start3_tensor, input_5_01_cropping_end3_tensor, input_5_01_cropping_axes_tensor, input_5_01_cropping_steps_tensor, input_5_01_cropping03_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_conv_node( conv1d_2_auto_pad, conv1d_2_dilations, &conv1d_2_group, conv1d_2_kernel_shape, NULL, conv1d_2_strides, adjusted_input1_tensor, conv1d_2_kernel_0_tensor, NULL, convolution_output1_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_105_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_squeeze_node( input_5_01_cropping0_tensor, _v_105_tensor, model_2_tf_op_layer_strided_slice_5_strided_slice_5_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_106_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_squeeze_node( input_5_01_cropping01_tensor, _v_106_tensor, model_2_tf_op_layer_strided_slice_7_strided_slice_7_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_107_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_squeeze_node( input_5_01_cropping02_tensor, _v_107_tensor, model_2_tf_op_layer_strided_slice_4_strided_slice_4_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_108_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_squeeze_node( input_5_01_cropping03_tensor, _v_108_tensor, model_2_tf_op_layer_strided_slice_6_strided_slice_6_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_transpose_node( Transpose3_perm, convolution_output1_tensor, transpose_output1_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_matmul_node( model_2_tf_op_layer_strided_slice_4_strided_slice_4_0_tensor, model_2_lstm_6_MatMul_1_ReadVariableOp_resource_0_tensor, model_2_lstm_6_MatMul_1_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_matmul_node( model_2_tf_op_layer_strided_slice_6_strided_slice_6_0_tensor, model_2_lstm_7_MatMul_1_ReadVariableOp_resource_0_tensor, model_2_lstm_7_MatMul_1_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_119_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_reducemean_node( &model_2_instant_layer_normalization_1_Mean_reduce_min_keepdims, NULL, transpose_output1_tensor, NULL, model_2_instant_layer_normalization_1_Mean_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_sub_node( transpose_output1_tensor, model_2_instant_layer_normalization_1_Mean_0_tensor, model_2_instant_layer_normalization_1_sub_1_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_mul_node( model_2_instant_layer_normalization_1_sub_1_0_tensor, model_2_instant_layer_normalization_1_sub_1_0_tensor, model_2_instant_layer_normalization_1_Square_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_120_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_reducemean_node( &model_2_instant_layer_normalization_1_Mean_1_reduce_min_keepdims, NULL, model_2_instant_layer_normalization_1_Square_0_tensor, NULL, model_2_instant_layer_normalization_1_Mean_1_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_add_node( model_2_instant_layer_normalization_1_Mean_1_0_tensor, model_2_instant_layer_normalization_1_add_y_0_tensor, model_2_instant_layer_normalization_1_add_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_sqrt_node( model_2_instant_layer_normalization_1_add_0_tensor, model_2_instant_layer_normalization_1_Sqrt_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_div_node( model_2_instant_layer_normalization_1_sub_1_0_tensor, model_2_instant_layer_normalization_1_Sqrt_0_tensor, model_2_instant_layer_normalization_1_truediv_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_mul_node( model_2_instant_layer_normalization_1_truediv_0_tensor, model_2_instant_layer_normalization_1_mul_ReadVariableOp_resource_0_tensor, model_2_instant_layer_normalization_1_mul_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_add_node( model_2_instant_layer_normalization_1_mul_0_tensor, model_2_instant_layer_normalization_1_add_1_ReadVariableOp_resource_0_tensor, model_2_instant_layer_normalization_1_add_1_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_transpose_node( model_2_lstm_6_transpose_perm, model_2_instant_layer_normalization_1_add_1_0_tensor, model_2_lstm_6_transpose_0_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_109_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_squeeze_node( model_2_lstm_6_transpose_0_tensor, _v_109_tensor, model_2_lstm_6_unstack_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_gemm_node(&Gemm28825_alpha, &Gemm28825_beta, &Gemm28825_transA, &Gemm28825_transB, model_2_lstm_6_unstack_0_tensor, model_2_lstm_6_MatMul_ReadVariableOp_resource_0_tensor, model_2_lstm_6_MatMul_1_0_tensor, model_2_lstm_6_add_0_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_add_node( model_2_lstm_6_add_0_tensor, model_2_lstm_6_BiasAdd_ReadVariableOp_resource_0_tensor, model_2_lstm_6_BiasAdd_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_split_node( &model_2_lstm_6_split_split_dim_0_split_axis, &model_2_lstm_6_split_split_dim_0_split_num_outputs, model_2_lstm_6_BiasAdd_0_tensor, NULL, model_2_lstm_6_split_0_tensor, model_2_lstm_6_split_1_tensor, model_2_lstm_6_split_2_tensor, model_2_lstm_6_split_3_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_sigmoid_node( model_2_lstm_6_split_3_tensor, model_2_lstm_6_Sigmoid_2_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_sigmoid_node( model_2_lstm_6_split_1_tensor, model_2_lstm_6_Sigmoid_1_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_sigmoid_node( model_2_lstm_6_split_0_tensor, model_2_lstm_6_Sigmoid_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_tanh_node( model_2_lstm_6_split_2_tensor, model_2_lstm_6_Tanh_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_mul_node( model_2_lstm_6_Sigmoid_1_0_tensor, model_2_tf_op_layer_strided_slice_5_strided_slice_5_0_tensor, model_2_lstm_6_mul_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_mul_node( model_2_lstm_6_Sigmoid_0_tensor, model_2_lstm_6_Tanh_0_tensor, model_2_lstm_6_mul_1_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_add_node( model_2_lstm_6_mul_0_tensor, model_2_lstm_6_mul_1_0_tensor, model_2_lstm_6_add_1_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_110_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_unsqueeze_node( model_2_lstm_6_add_1_0_tensor, _v_110_tensor, model_2_tf_op_layer_stack_4_stack_4_unsqueeze00_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_tanh_node( model_2_lstm_6_add_1_0_tensor, model_2_lstm_6_Tanh_1_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_mul_node( model_2_lstm_6_Sigmoid_2_0_tensor, model_2_lstm_6_Tanh_1_0_tensor, model_2_lstm_6_mul_2_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_111_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_unsqueeze_node( model_2_lstm_6_mul_2_0_tensor, _v_111_tensor, model_2_tf_op_layer_stack_3_stack_3_unsqueeze00_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_112_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_unsqueeze_node( model_2_lstm_6_mul_2_0_tensor, _v_112_tensor, model_2_lstm_6_stack_unsqueeze00_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_113_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_squeeze_node( model_2_lstm_6_stack_unsqueeze00_tensor, _v_113_tensor, model_2_lstm_7_unstack_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_gemm_node(&Gemm11550_alpha, &Gemm11550_beta, &Gemm11550_transA, &Gemm11550_transB, model_2_lstm_7_unstack_0_tensor, model_2_lstm_7_MatMul_ReadVariableOp_resource_0_tensor, model_2_lstm_7_MatMul_1_0_tensor, model_2_lstm_7_add_0_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_add_node( model_2_lstm_7_add_0_tensor, model_2_lstm_7_BiasAdd_ReadVariableOp_resource_0_tensor, model_2_lstm_7_BiasAdd_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_split_node( &model_2_lstm_7_split_split_dim_0_split_axis, &model_2_lstm_7_split_split_dim_0_split_num_outputs, model_2_lstm_7_BiasAdd_0_tensor, NULL, model_2_lstm_7_split_0_tensor, model_2_lstm_7_split_1_tensor, model_2_lstm_7_split_2_tensor, model_2_lstm_7_split_3_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_sigmoid_node( model_2_lstm_7_split_3_tensor, model_2_lstm_7_Sigmoid_2_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_sigmoid_node( model_2_lstm_7_split_1_tensor, model_2_lstm_7_Sigmoid_1_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_sigmoid_node( model_2_lstm_7_split_0_tensor, model_2_lstm_7_Sigmoid_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_tanh_node( model_2_lstm_7_split_2_tensor, model_2_lstm_7_Tanh_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_mul_node( model_2_lstm_7_Sigmoid_1_0_tensor, model_2_tf_op_layer_strided_slice_7_strided_slice_7_0_tensor, model_2_lstm_7_mul_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_mul_node( model_2_lstm_7_Sigmoid_0_tensor, model_2_lstm_7_Tanh_0_tensor, model_2_lstm_7_mul_1_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_add_node( model_2_lstm_7_mul_0_tensor, model_2_lstm_7_mul_1_0_tensor, model_2_lstm_7_add_1_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_114_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_unsqueeze_node( model_2_lstm_7_add_1_0_tensor, _v_114_tensor, model_2_tf_op_layer_stack_4_stack_4_unsqueeze10_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_tanh_node( model_2_lstm_7_add_1_0_tensor, model_2_lstm_7_Tanh_1_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_concat_node(&model_2_tf_op_layer_stack_4_stack_4_concat_axis, model_2_tf_op_layer_stack_4_stack_4_0_tensor, 2, model_2_tf_op_layer_stack_4_stack_4_unsqueeze00_tensor, model_2_tf_op_layer_stack_4_stack_4_unsqueeze10_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_mul_node( model_2_lstm_7_Sigmoid_2_0_tensor, model_2_lstm_7_Tanh_1_0_tensor, model_2_lstm_7_mul_2_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_115_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_unsqueeze_node( model_2_tf_op_layer_stack_4_stack_4_0_tensor, _v_115_tensor, model_2_tf_op_layer_stack_5_stack_5_unsqueeze10_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_116_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_unsqueeze_node( model_2_lstm_7_mul_2_0_tensor, _v_116_tensor, model_2_tf_op_layer_stack_3_stack_3_unsqueeze10_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_117_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_unsqueeze_node( model_2_lstm_7_mul_2_0_tensor, _v_117_tensor, model_2_lstm_7_stack_unsqueeze00_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_concat_node(&model_2_tf_op_layer_stack_3_stack_3_concat_axis, model_2_tf_op_layer_stack_3_stack_3_0_tensor, 2, model_2_tf_op_layer_stack_3_stack_3_unsqueeze00_tensor, model_2_tf_op_layer_stack_3_stack_3_unsqueeze10_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_constant_node( _tensor, NULL, NULL, NULL, NULL, _v_118_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_unsqueeze_node( model_2_tf_op_layer_stack_3_stack_3_0_tensor, _v_118_tensor, model_2_tf_op_layer_stack_5_stack_5_unsqueeze00_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_transpose_node( model_2_lstm_7_transpose_1_perm, model_2_lstm_7_stack_unsqueeze00_tensor, model_2_lstm_7_transpose_1_0_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_concat_node(&model_2_tf_op_layer_stack_5_stack_5_concat_axis, tf_op_layer_stack_5_tensor, 2, model_2_tf_op_layer_stack_5_stack_5_unsqueeze00_tensor, model_2_tf_op_layer_stack_5_stack_5_unsqueeze10_tensor );
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_reshape_node( model_2_lstm_7_transpose_1_0_tensor, shape_tensor1_tensor, model_2_dense_3_Tensordot_Reshape_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_matmul_node( model_2_dense_3_Tensordot_Reshape_0_tensor, model_2_dense_3_Tensordot_Reshape_1_0_tensor, model_2_dense_3_Tensordot_MatMul_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_reshape_node( model_2_dense_3_Tensordot_MatMul_0_tensor, shape_tensor_tensor, model_2_dense_3_Tensordot_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_add_node( model_2_dense_3_Tensordot_0_tensor, model_2_dense_3_BiasAdd_ReadVariableOp_resource_0_tensor, model_2_dense_3_BiasAdd_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_sigmoid_node( model_2_dense_3_BiasAdd_0_tensor, model_2_activation_3_Sigmoid_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_mul_node( transpose_output1_tensor, model_2_activation_3_Sigmoid_0_tensor, model_2_multiply_2_mul_0_tensor);
	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_transpose_node( Transpose_perm, model_2_multiply_2_mul_0_tensor, adjusted_input_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_conv_node( conv1d_3_auto_pad, conv1d_3_dilations, &conv1d_3_group, conv1d_3_kernel_shape, conv1d_3_pads, conv1d_3_strides, adjusted_input_tensor, conv1d_3_kernel_0_tensor, NULL, convolution_output_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	new_node = create_transpose_node( PushTranspose_1_perm, convolution_output_tensor, conv1d_3_tensor);
 	if(new_node == 0) return 0;
	push_back_list( &m->node, new_node );
	return 1;
}

#endif //MODEL__H
